### ISSUE TITLE
Icon in tab

### ISSUE THREAD

**Issue by RavenclawZo** [RavenclawZo/RavenclawZo.github.io#2]
Need to make an icon in tab, tried doing what several sites suggested. Help?

**Comment by rywarsaw** [comment]
@RavenclawZo 

You can just add the following line to your HTML and put the icon in a assets folder.

```
<link rel="icon" type="image/png" href="assets/favicon.ico">
```

Then put a Favicon.ico file in your assets folder, must be a sub-folder of the top directory (where your index.html is).
